-- ---------------------------------------------------
-- Lab: SQL Joins (Sakila Database)
-- ---------------------------------------------------

USE sakila;

-- ---------------------------------------------------
-- 1. List the number of films per category
-- ---------------------------------------------------
SELECT 
    c.name AS category,
    COUNT(f.film_id) AS film_count
FROM film f
INNER JOIN film_category fc ON f.film_id = fc.film_id
INNER JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY film_count DESC;

-- ---------------------------------------------------
-- 2. Retrieve the store ID, city, and country for each store
-- ---------------------------------------------------
SELECT 
    s.store_id,
    ci.city,
    co.country
FROM store s
INNER JOIN address a ON s.address_id = a.address_id
INNER JOIN city ci ON a.city_id = ci.city_id
INNER JOIN country co ON ci.country_id = co.country_id
ORDER BY s.store_id;

-- ---------------------------------------------------
-- 3. Calculate the total revenue generated by each store in dollars
-- ---------------------------------------------------
SELECT 
    s.store_id,
    SUM(p.amount) AS total_revenue
FROM payment p
INNER JOIN staff st ON p.staff_id = st.staff_id
INNER JOIN store s ON st.store_id = s.store_id
GROUP BY s.store_id
ORDER BY total_revenue DESC;

-- ---------------------------------------------------
-- 4. Determine the average running time of films for each category
-- ---------------------------------------------------
SELECT 
    c.name AS category,
    ROUND(AVG(f.length), 2) AS avg_running_time
FROM film f
INNER JOIN film_category fc ON f.film_id = fc.film_id
INNER JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY avg_running_time DESC;

-- ---------------------------------------------------
-- BONUS 5. Identify the film categories with the longest average running time
-- ---------------------------------------------------
SELECT 
    c.name AS category,
    ROUND(AVG(f.length), 2) AS avg_running_time
FROM film f
INNER JOIN film_category fc ON f.film_id = fc.film_id
INNER JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY avg_running_time DESC
LIMIT 5;

-- ---------------------------------------------------
-- BONUS 6. Display the top 10 most frequently rented movies
-- ---------------------------------------------------
SELECT 
    f.title,
    COUNT(r.rental_id) AS rental_count
FROM film f
INNER JOIN inventory i ON f.film_id = i.film_id
INNER JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

-- ---------------------------------------------------
-- BONUS 7. Determine if "Academy Dinosaur" can be rented from Store 1
-- ---------------------------------------------------
SELECT 
    f.title,
    s.store_id,
    CASE 
        WHEN i.inventory_id IS NOT NULL THEN 'Available'
        ELSE 'Not Available'
    END AS availability
FROM film f
LEFT JOIN inventory i ON f.film_id = i.film_id
LEFT JOIN store s ON i.store_id = s.store_id
WHERE f.title = 'ACADEMY DINOSAUR' AND s.store_id = 1;

-- ---------------------------------------------------
-- BONUS 8. List all distinct film titles with availability status
-- ---------------------------------------------------
SELECT 
    f.title,
    CASE 
        WHEN IFNULL(i.inventory_id, 0) = 0 THEN 'NOT available'
        ELSE 'Available'
    END AS availability
FROM film f
LEFT JOIN inventory i ON f.film_id = i.film_id
GROUP BY f.title
ORDER BY f.title ASC;
